---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    service.kubernetes.io/ibm-load-balancer-cloud-provider-ip-type: private
  labels:
    app: guestbook
    tier: frontend
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  type: LoadBalancer
  #loadBalancerIP: 192.168.50.3
  #loadBalancerSourceRanges:
  #- "192.168.50.0/24"
  ports:
  - port: 80
  selector:
    app: guestbook
    tier: frontend
